services:
  fastapi:
    volumes:
      - ./fastapi-stratint:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  react:
    build:
      context: ./react-stratint
      dockerfile: Dockerfile
      target: builder
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: pnpm run dev -- --host 0.0.0.0
    volumes:
      - ./react-stratint:/app
      - /app/node_modules
